CREATE TABLE IF NOT EXISTS `#__jtour_tours`(
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
   `price` VARCHAR(255) NOT NULL,
  `description` TEXT DEFAULT NULL,
  `create_on` DATETIME NOT NULL,
  `update_on` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `checked_out` INT(11) NOT NULL DEFAULT 0,
  `checked_out_time` DATETIME DEFAULT NULL,
  `ordering` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  `published` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `#__jtour_excursions`(
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT DEFAULT NULL,
  `price` DECIMAL(10, 0) UNSIGNED NOT NULL,
  `duration`  VARCHAR(30) NOT NULL,
  `workdays` CHAR(100) NOT NULL,
  `schedule` TEXT NOT NULL,
  `create_on` DATETIME NOT NULL,
  `update_on` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   `published` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `#__jtour_reports`(
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `report` TEXT NOT NULL,
  `price` VARCHAR(255) NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `create_on` DATETIME NOT NULL,
  `update_on` TIMESTAMP DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8;



CREATE TABLE IF NOT EXISTS `#__jtour_excursion_to_tour` (
  `tour_id` INT(11) UNSIGNED NOT NULL,
  `excursion_id` INT(11) UNSIGNED NOT NULL
)
ENGINE = INNODB
CHARACTER SET utf8;